""" 
Constants file
"""
KEYCLOAK_CLIENT_ID = 'KEYCLOAK_CLIENT_ID'
KEYCLOAK_CLIENT_SECRET = 'KEYCLOAK_CLIENT_SECRET'
KEYCLOAK_CALLBACK_URL = 'KEYCLOAK_CALLBACK_URL'
KEYCLOAK_METADATA_URL = 'KEYCLOAK_METADATA_URL'
PROFILE_KEY = 'profile'
SECRET_KEY = 'ThisIsTheSecretKey'
JWT_PAYLOAD = 'jwt_payload'

